// Generated by gencpp from file pix_can/CANTestInfo.msg
// DO NOT EDIT!


#ifndef PIX_CAN_MESSAGE_CANTESTINFO_H
#define PIX_CAN_MESSAGE_CANTESTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pix_can
{
template <class ContainerAllocator>
struct CANTestInfo_
{
  typedef CANTestInfo_<ContainerAllocator> Type;

  CANTestInfo_()
    : header()
    , current_wheel(0)
    , target_wheel(0)  {
    }
  CANTestInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_wheel(0)
    , target_wheel(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _current_wheel_type;
  _current_wheel_type current_wheel;

   typedef uint16_t _target_wheel_type;
  _target_wheel_type target_wheel;





  typedef boost::shared_ptr< ::pix_can::CANTestInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pix_can::CANTestInfo_<ContainerAllocator> const> ConstPtr;

}; // struct CANTestInfo_

typedef ::pix_can::CANTestInfo_<std::allocator<void> > CANTestInfo;

typedef boost::shared_ptr< ::pix_can::CANTestInfo > CANTestInfoPtr;
typedef boost::shared_ptr< ::pix_can::CANTestInfo const> CANTestInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pix_can::CANTestInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pix_can::CANTestInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pix_can::CANTestInfo_<ContainerAllocator1> & lhs, const ::pix_can::CANTestInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.current_wheel == rhs.current_wheel &&
    lhs.target_wheel == rhs.target_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pix_can::CANTestInfo_<ContainerAllocator1> & lhs, const ::pix_can::CANTestInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pix_can

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pix_can::CANTestInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pix_can::CANTestInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pix_can::CANTestInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pix_can::CANTestInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pix_can::CANTestInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pix_can::CANTestInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pix_can::CANTestInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f942539659fc3310c68f769b65513a00";
  }

  static const char* value(const ::pix_can::CANTestInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf942539659fc3310ULL;
  static const uint64_t static_value2 = 0xc68f769b65513a00ULL;
};

template<class ContainerAllocator>
struct DataType< ::pix_can::CANTestInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pix_can/CANTestInfo";
  }

  static const char* value(const ::pix_can::CANTestInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pix_can::CANTestInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint16 current_wheel\n"
"uint16 target_wheel\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pix_can::CANTestInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pix_can::CANTestInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_wheel);
      stream.next(m.target_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANTestInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pix_can::CANTestInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pix_can::CANTestInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_wheel: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.current_wheel);
    s << indent << "target_wheel: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIX_CAN_MESSAGE_CANTESTINFO_H
